# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocktailsAppSwiftUI2.0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocktailsAppSwiftUI2.0
pod 'SQLite.swift', '~> 0.12.0'
end
